name: publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TAG
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Publish ${{ matrix.svc }}
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/clipsketch-ai:latest
            ghcr.io/${{ github.repository_owner }}/clipsketch-ai:${{ env.TAG }}
            earisty/clipsketch-ai:${{ env.TAG }}
            earisty/clipsketch-ai:latest
